---
- hosts: "{{ hosts }}"
  become: true
  tasks: 
    - name: Create a directory /var/tmp/prueba123
      file:
        path: /var/tmp/prueba123
        state: directory
      when: ansible_default_ipv4.address == "192.168.17.106"