---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: instalamos apache
      package:
        name: httpd
        state: latest
      tags: install
    - name: httpd start and enabled
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config
    - name: Create index.html
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config
    - name: add content to index.html
      copy:
        content: "<br><h1> eeeeeiiii you </h1><br><b> eres muy feo</b>"
        dest: /var/www/html/index.html
      tags: config
    - name: uninstall apache
      package:
        name: httpd
        state: absent
      tags: uinstall

